### ISSUE TITLE
/remove and /reset not working with initial watchlist

### ISSUE THREAD

**Issue by drag0no** [algoni/PogoBot-Telegram#13]
Well, this thing a little bit complicated. I write what i did step by step.
1. Had a big initial watchlist in config.json with: Magmar, Scyther, Electrabazz, Snorlax, Dragonite, Lapras etc.
2. Started bot.
3. Removed Magmar, Scyther, Electrabazz from the list through /remove command .
4. Bot still alerted me about these pokemons. ( /remove did nothing )
5. I deleted these pokemons (Magmar, Scyther, Electrabazz) from the initial watchlist in config.json .
6. Restarted bot.
7. Used /reset .
8. Bot still sent me notifications about these pokemons.
9. Used /remove .
10. Bot still send me notification.

Nothing helps. :(

![image](https://cloud.githubusercontent.com/assets/20945307/17580816/1d9281e6-5faa-11e6-88e1-d2a16b44cb9e.png)

![image](https://cloud.githubusercontent.com/assets/20945307/17580821/2a25ab7c-5faa-11e6-8229-d243bcc6fc6c.png)

**Comment by s-hirvonen** [comment]
Mine seems to work just as expected:

![image](https://cloud.githubusercontent.com/assets/2066504/17582124/8e4533c2-5fb2-11e6-80c5-128c982deb49.png)

Using latest develop branch. Which commit are you on?

**Comment by drag0no** [comment]
a8377845dc1f182e19a60e07bd288dc99d711221 - the latest one. 

May be it's connected with this bug, that i had before: https://www.reddit.com/r/pokemongodev/comments/4wryhk/pogobottelegram_onthego_configurable/d6ae2b0 ?

Btw, I'm Rinskilla on reddit ;)

**Comment by drag0no** [comment]
In addition, if u didnt notice... When I /remove Magmar it's actually removed from the /list as you can see, but I still get notifications about him. Thats why i attach screenshot with the list.

**Comment by s-hirvonen** [comment]
Okay, I see. I can /add and /remove Pidgey and it works as expected. However, I noticed that /start curently doesn't put an existing user active. Will fix.

**Comment by s-hirvonen** [comment]
If still doesn't work, try resetting your database. Use mongo.exe (not mongod), and do

```
use pogobot
db.users.find()   # lists users and their lists, see if there's anything funny
db.users.remove() # deletes all user and lists
```
