### ISSUE TITLE
Suggestion: Add a link to a googlemaps in text fromat

### ISSUE THREAD

**Issue by drag0no** [algoni/PogoBot-Telegram#14]
Sometimes you need more detailed view than just a screenshot.
I think that one line with link is not a problem. ;)

![image](https://cloud.githubusercontent.com/assets/20945307/17580872/9a3e711e-5faa-11e6-9e2d-41735d4b3d0e.png)

**Comment by s-hirvonen** [comment]
I was thinking of using Telegram bot's URL buttons for this, like this one:

![](https://core.telegram.org/file/811140999/1/2JSoUVlWKa0/4fad2e2743dc8eda04)

However, the library I use doesn't support them on images, only text messages :( There's a pull request that fixes it yagop/node-telegram-bot-api#160 but it's not merged yet.

**Comment by drag0no** [comment]
Button is a good idea! :+1:  But dont u think, that it takes too much space?

**Comment by drag0no** [comment]
Button is rly good. And two message system too. Bot is complete for current version? :smiley:
