### ISSUE TITLE
[Poll] Should the bot send photo and text as separate messages?

### ISSUE THREAD

**Issue by s-hirvonen** [algoni/PogoBot-Telegram#15]
One of the things that annoy me about the Telegram app is that when sending photos the notification doesn't  display the caption. All I get (on Android) is "bot sent you a photo" and I have to open the app to see what poke it was.

One thing I could do is send the photo and then immediately the text as a new message,  so you'd get 

"A wild Pidgey appeared"
"bot sent you a photo"

What do you think? Is it more spammy?

**Comment by drag0no** [comment]
You can add this feature. We will test it, if it will be too spamy or mb annoying, we will write about this in this topic and you can revert this feature. 

It's all up to you. :+1: I dont mind to test it. ;)

**Comment by s-hirvonen** [comment]
There's now a branch feature/alt-notification for testing this.

**Comment by drag0no** [comment]
For me, both ways are good. First impression - second one a little bit better! :wink:
