### ISSUE TITLE
"<time> left" issue

### ISSUE THREAD

**Issue by drag0no** [algoni/PogoBot-Telegram#16]
Sometimes "<time> left" says something strange.

![image](https://cloud.githubusercontent.com/assets/20945307/17587140/130b79d8-5fcf-11e6-8ed5-42e66bf74340.png)

I will try investigate it a little bit deeper.

**Comment by drag0no** [comment]
More info, found it in log:

![image](https://cloud.githubusercontent.com/assets/20945307/17587238/9e74275e-5fcf-11e6-908c-84829de8246d.png)

It is linked with this buggy Slowpoke timer

**Comment by s-hirvonen** [comment]
Was that the same Slowpoke spawnpoint as the one above?

**Comment by drag0no** [comment]
Nope, two different. 

![image](https://cloud.githubusercontent.com/assets/20945307/17587912/df6f41cc-5fd3-11e6-8e27-6219652efce9.png)

Last one (the buggy one) seems outdated somehow.

**Comment by s-hirvonen** [comment]
Okay, it could be that the map's webhook sometimes sends expired spawns. If it's the case then it's easy to just ignore them
