### ISSUE TITLE
Not recieving telegram messages

### ISSUE THREAD

**Issue by Kikkah** [algoni/PogoBot-Telegram#17]
I have everything setup and running.

The node app.js is running and tells me a user (me) is now active on the bot. However, the bot is not sending my any messages about pokemon on my watchlist.

For now I decided to put the most common up in my area e.g.
    "watchlist": [
        "Pidgey",
        "Ratata",
        "Weedle",
        "Magikarp",
        "Poliwag"
    ]

But I do not receive any messages. What could be the issue?

**Comment by s-hirvonen** [comment]
What console output do you get when running the bot?

**Comment by Kikkah** [comment]
Info: Connected to Mongodb on mongodb://localhost/pogobot
Info: Express listening on port 4000

And when I do /start in Telegram it will give a message that my user is connected, but that is about it.

**Comment by s-hirvonen** [comment]
Okay, the console should be filled with messages from encounters, like

```
info: Wild Pidgeotto appeared!   Disappear time 1471079561       Users watching          Seen pokemon 226
info: Wild Rattata appeared!     Disappear time 1471080092       Users watching          Seen pokemon 227
info: Wild Rattata appeared!     Disappear time 1471079864       Users watching          Seen pokemon 228
info: Wild Paras appeared!       Disappear time 1471079533       Users watching          Seen pokemon 229
info: Wild Caterpie appeared!    Disappear time 1471080106       Users watching          Seen pokemon 230
```

Start PokemonGo-Map by passing `-wh http://127.0.0.1:4000`

**Comment by tinghua81** [comment]
Sorry, I had the same problem. Could anybody help me?
My PokemonGo-Map and Telegram console both work well, but Telegram Bot in my phone didn't send the message to me.
I already did `/start`. Telegram also gave me a message that "Bot activated", but that is about it.
Telegram console is like below:
![screenshot from 2016-08-16 02 09 12](https://cloud.githubusercontent.com/assets/17688268/17674200/1fdecb7a-6357-11e6-9491-bfa45078c98f.png)

Thanks.

**Comment by algoni** [comment]
Did you enable the webhook on the map?

**Comment by tinghua81** [comment]
I started PokemonGo-Map by passing following code:

```
python ./runserver.py -a ptc -u "USERNAME" -p "PASSWORD" -l "lat/lng"
-st 3 -k "maps key" -wh "http://127.0.0.1:4000"
```

The map works well. Telegram console also shows the messages, but nothing
be sent to my phone.

I tried to do it in many ways, but it still failed. If you have any
suggestions, please let me know!!!

Thanks for your helps.

**Comment by xdrushxd** [comment]
Did you install and start the service mongodb ?

**Comment by tinghua81** [comment]
@xdrushxd 
Sure! I did. The program works without errors.

**Comment by s-hirvonen** [comment]
Do you ever get a line on your console where it says Users watching <your telegram id>?

**Comment by tinghua81** [comment]
@algoni 
Yes, the image that I posted yesterday was on my console.

**Comment by s-hirvonen** [comment]
Yeah but do you get your telegram ID there? The console reports all spawns it sees, not only those you are watching. Try adding Pidgey or Rattata and see if it triggers
