### ISSUE TITLE
ignore list

### ISSUE THREAD

**Issue by houkop** [algoni/PogoBot-Telegram#18]
hello!
how can I setup ignore list?
I don't want waste my google api key for pidgeys and rattatas...
Is there any way to do this?

**Comment by houkop** [comment]
or, maybe you can do a check - generate a map only if somebody waiting for this pokemon, that will be great reduction of api usage!

**Comment by s-hirvonen** [comment]
This is how it currently works on develop; static map image is requested only if there are active users with that pokemon on their list.

**Comment by houkop** [comment]
nope. I'm on develop and if you add pokemon to list and block a bot, it still will generate maps and try to send it to you.
