### ISSUE TITLE
doesn't create .tmp folder

### ISSUE THREAD

**Issue by gmkbenjamin** [algoni/PogoBot-Telegram#2]
Issue:

If .tmp folder doesn't exist
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open 'C:\pg\PogoBot-Telegram.tmp\MTg0NDY3NDQwNzM0NDAyOTIwNjY=.png'
    at Error (native)

OS: Windows 10 Pro 64bit
Commit: 6148bd596dd24bdc54fc81f16b9c11e287719ada

**Comment by s-hirvonen** [comment]
Fixed in a644047ee: images are no longer saved to disk, they are sent as buffers so .tmp won't grow huge and is no longer needed.
