### ISSUE TITLE
Cannot start pogobot

### ISSUE THREAD

**Issue by samwiseg0** [algoni/PogoBot-Telegram#24]
I am sure I am missing something. I have setup mongodb and created the database and inserted data into it but I still cannot seem to have it start. What could the issue be? 

config changed to 
`"mongodb": "mongodb://localhost:27017/pogobot",`

Service is started and listening

```
netstat -ano | grep 27017
tcp        0      0     127.0.0.1:27017         0.0.0.0:*               LISTEN      off   (0.00/0/0)
unix  2      [ ACC ]     STREAM     LISTENING     85847153 /tmp/mongodb-27017.sock
```

```
npm start
> pogobot-telegram@0.0.4 start /webapps/PogoBot-Telegram
> node app.js


/webapps/PogoBot-Telegram/node_modules/mongoose/lib/connection.js:282
  var promise = new Promise.ES6(function(resolve, reject) {
                ^
TypeError: undefined is not a function
    at NativeConnection.Connection.open (/webapps/PogoBot-Telegram/node_modules/mongoose/lib/connection.js:282:17)
    at Mongoose.connect (/webapps/PogoBot-Telegram/node_modules/mongoose/lib/index.js:241:47)
    at Object.<anonymous> (/webapps/PogoBot-Telegram/app.js:11:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! weird error 8
npm ERR! not ok code 0

```

Thanks

**Comment by s-hirvonen** [comment]
Seems like you're using an old version of node that doesn't have promises, which is required by mongoose.

Node.js version 4.5.0 is the current LTS release, try if upgrading fixes it.

**Comment by samwiseg0** [comment]
Ok I removed "mongoose.Promise = global.Promise;" from app.js and it seems to work just fine. I will try upgrading it to see if that solves it. I am using centos 7 and this is the latest version that was available with the default repos. 

```
node -v
v0.10.46
```

**Comment by s-hirvonen** [comment]
OK, that will also work. Mongoose displays a deprecation notice when starting, but if you can live with that then it's not a problem :)
