### ISSUE TITLE
Enhancement - Option to send the location via Telegrams sendLocation method

### ISSUE THREAD

**Issue by samwiseg0** [algoni/PogoBot-Telegram#25]
It would be nice to have the ability to have the bot send the location of the pokemon using the sendLocation method with the silent flag set. It would allow the user to click strait to a map that they can navigate to. 

[edit] This would be in place of the picture. It would be nice to have the option so that way 2 notifications can be avoided as the location can be sent silently

**Comment by s-hirvonen** [comment]
I pushed a branch feature/sendLocation where this can be tested. Currently no option to change notification styles via config though.

**Comment by samwiseg0** [comment]
This is perfect! much better user experience. Thanks!
