### ISSUE TITLE
watchlist

### ISSUE THREAD

**Issue by gmkbenjamin** [algoni/PogoBot-Telegram#4]
Issue:
Updating watchlist in config file doesn't update it in database. 
Great app!

OS: Windows 10 Pro 64bit
Commit: 6148bd5

**Comment by s-hirvonen** [comment]
This is (at the moment) the intended behavior; the watchlist in config.json is the baseline new users start with, and they can customize their lists by /add and /remove commands.

This way a user's custom list doesn't get reset whenever the config file changes, losing all their changes.

However, a `/reset` command could be implemented, which sets the users list to what's currently in the config file.
