### ISSUE TITLE
node app.js fails on my system

### ISSUE THREAD

**Issue by abchikama** [algoni/PogoBot-Telegram#7]
When I start npm install I get this message 

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogobot-telegram@0.0.3 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogobot-telegram@0.0.3 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogobot-telegram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogobot-telegram
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogobot-telegram
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Test\Desktop\PogoBot-Telegram\npm-debug.log

Contents of npm-debug.log 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pogobot-telegram@0.0.3~prestart: pogobot-telegram@0.0.3
6 silly lifecycle pogobot-telegram@0.0.3~prestart: no script for prestart, continuing
7 info lifecycle pogobot-telegram@0.0.3~start: pogobot-telegram@0.0.3
8 verbose lifecycle pogobot-telegram@0.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle pogobot-telegram@0.0.3~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Test\Desktop\PogoBot-Telegram\node_modules.bin;C:\Program Files\nodejs;C:\Users\Test\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Test\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Instant Reality\bin;C:\Program Files (x86)\B1 Free Archiver;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Instant Reality\bin;C:\Program Files (x86)\B1 Free Archiver;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\Users\Test\AppData\Roaming\npm;C:\Python27;C:\Python27\Scripts;C:\Python27;C:\Python27\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle pogobot-telegram@0.0.3~start: CWD: C:\Users\Test\Desktop\PogoBot-Telegram
11 silly lifecycle pogobot-telegram@0.0.3~start: Args: [ '/d /s /c', 'node app.js' ]
12 silly lifecycle pogobot-telegram@0.0.3~start: Returned: code: 1  signal: null
13 info lifecycle pogobot-telegram@0.0.3~start: Failed to exec start script
14 verbose stack Error: pogobot-telegram@0.0.3 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pogobot-telegram@0.0.3
16 verbose cwd C:\Users\Test\Desktop\PogoBot-Telegram
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error pogobot-telegram@0.0.3 start: `node app.js`
22 error Exit status 1
23 error Failed at the pogobot-telegram@0.0.3 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pogobot-telegram package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pogobot-telegram
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pogobot-telegram
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by s-hirvonen** [comment]
What's the output if you start it with `node app.js`?

**Comment by abchikama** [comment]
C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\nconf\lib\nconf\stores\file.
js:141
      throw new Error("Error parsing your configuration file: [" + self.file + '
]: ' + ex.message);
      ^

Error: Error parsing your configuration file: [./config.json]: Unexpected token
P in JSON at position 168
    at File.loadSync (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\nconf\
lib\nconf\stores\file.js:141:13)
    at Provider.add (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\nconf\l
ib\nconf\provider.js:137:23)
    at Provider.file (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\nconf\
lib\nconf\provider.js:63:15)
    at module.exports (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\confi
g.json\lib\config.js:22:11)
    at Object.<anonymous> (C:\Users\Test\Desktop\PogoBot-Telegram\app.js:6:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by s-hirvonen** [comment]
So your config.json seems malformed. Make sure it's valid JSON.

**Comment by abchikama** [comment]
Is it possible I may have used invalid characters, because when I go online it says that my path to mongoDB contains invalid characters 

{
    "api_token": "SECRET",
    "gmap_key": "SECRET",
    "port": 4000,
    "mongodb": **"C:\Program Files\MongoDB\Server"**,
    "watchlist": [
        "Venusaur",
        "Blastoise",
        "Charizard",
        "Dragonite"
    ]
}

**Comment by s-hirvonen** [comment]
the default uri for mongodb should work in 99% cases.

**Comment by abchikama** [comment]
When I do the default one, I get this 

> pogobot-telegram@0.0.3 start C:\Users\Test\Desktop\PogoBot-Telegram
> node app.js

error: Mongodb connection failed!

**Comment by s-hirvonen** [comment]
Is your mongod.exe running?

**Comment by abchikama** [comment]
No, how should I got about getting it started? when I click on it a CMD window opens up then closes immediately

**Comment by abchikama** [comment]
I was able to start mongod.exe bbut now this happens 

Unhandled rejection Error: 401 {"ok":false,"error_code":401,"description":"Unauthorized"}
    at C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegramPolling.js:126:17
    at tryCatcher (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Test\Desktop\PogoBot-Telegram\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)

and it repeats with the same error but different timers

**Comment by s-hirvonen** [comment]
Navigate to it from cmd and start it with `mondod.exe`. If you want to keep it always running, see http://stackoverflow.com/questions/2438055/how-to-run-mongodb-as-windows-service or similar solution.
